import React from 'react' 

export const metadata = {
    title: 'About',
    description: 'Generated by create next app',
}

const page = () => {
    return (
        <div>
            asd
        </div>
    )
}

export default page
